// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGADjOMB0thlEqb5Tp6zxk779NywDC5nQ',
    appId: '1:900330938562:web:f8dec4d61ba74d79ee9b5b',
    messagingSenderId: '900330938562',
    projectId: 'devansh-supplers',
    authDomain: 'devansh-supplers.firebaseapp.com',
    storageBucket: 'devansh-supplers.firebasestorage.app',
    measurementId: 'G-C9FPBDG13G',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGADjOMB0thlEqb5Tp6zxk779NywDC5nQ',
    appId: '1:900330938562:web:d5ccc08106c88d07ee9b5b',
    messagingSenderId: '900330938562',
    projectId: 'devansh-supplers',
    authDomain: 'devansh-supplers.firebaseapp.com',
    storageBucket: 'devansh-supplers.firebasestorage.app',
    measurementId: 'G-FPJ3MZQZ94',
  );
}
