name: Flutter CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.1'   # match your local `flutter --version`
          channel: 'stable'
      - name: Create .env
        run: |
          echo "${{ secrets.DOT_ENV }}" > .env

      - name: Install dependencies
        run: flutter pub get

      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Static analysis (fails on warnings/errors)
        run: flutter analyze --fatal-infos


      - name: Build web (sanity check it actually compiles)
        run: flutter build web --release